// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TextClassification.DB_data;

namespace TextClassification.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20220517182956_DocDBV2")]
    partial class DocDBV2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("TextClassification.DB_data.SaveClasificationOnDB", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("DocLang")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("dateCreateDocument")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("dateProcessingDocument")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("documentClass")
                        .HasColumnType("text");

                    b.Property<string>("documentName")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("DocumentClassification");
                });
#pragma warning restore 612, 618
        }
    }
}
